resolver: lts-13.22

packages:
- .
# - prelude
# - lorentz-contracts
# - indigo


extra-deps:
- aeson-options-0.1.0
- base58-bytestring-0.1.0
- constraints-0.11
- hex-text-0.1.0.0
- pretty-terminal-0.1.0.0
- show-type-0.1.1
- first-class-families-0.6.0.0@sha256:9d2a2a0092dfb8fd0e688b0b6bf71242fbc393c028b0b669d25ed387667490c2
- morley-0.5.0
- morley-prelude-0.3.0@sha256:9e9473ac14cfa206adf0a3700764c0251de05042f1fe45daf9cb8556079ae663

  # morley-0.5.0 doesn't come with a version of morley-ledgers on hackage
- git:
    https://gitlab.com/morley-framework/morley.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    4d825ab1ca9adcafa368a057b18bacfb220ae939 # 0.5.0
  subdirs:
    # - .
    # - prelude
    # - morley-upgradeable
    - morley-ledgers
    - morley-ledgers-test
    # - indigo

- git:
    https://github.com/tqtezos/lorentz-contract-param.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    f6434e40c10ede0261e9f76d1ef039d23f257a34 # 2.0.5.0.0
  subdirs:
    - .

# - aeson-options-0.1.0
# - base58-bytestring-0.1.0
# - hex-text-0.1.0.0
# - show-type-0.1.1
# - constraints-0.11.2@sha256:d028005d93f891b48b61ff0c82c6f868859eb728010dea3e355b0c55d0f57cf9
# - type-equality-1@sha256:aeb9c44abf5d2edf52caff114a7da565d8328fa84bbe194828e4355ea85bf5b3
# - git:
#     https://gitlab.com/morley-framework/morley.git
#     # ^ CI cannot use ssh, so we use http clone here
#   commit:
#     06bbe4e0cba9c1cf83bcf61b78666c6b5bb34c34 # master
#   subdirs:
#     - .
#     - lorentz-contracts
#     - prelude
#     - indigo

nix:
  shell-file: shell.nix
